spring.application.name=qlms-shipment-service
server.port=8082

# QLMS Azure PostgreSQL
spring.datasource.url=jdbc:postgresql://qlmsdb.postgres.database.azure.com:5432/qlms_shipment?sslmode=require
spring.datasource.username=qlmsadmin
spring.datasource.password=Qlms@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Kafka (disabled for now)
spring.kafka.bootstrap-servers=localhost:9092
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true